syntax = "proto3";

import "google/protobuf/empty.proto";

package authorization;

service AuthorizationService {
	rpc CheckOwnership(CheckOwnershipRequest) returns (CheckOwnershipResponse) {}
	rpc RegisterOwnership(RegisterOwnershipRequest) returns (google.protobuf.Empty) {}
	rpc RemoveOwnership(RemoveOwnershipRequest) returns (google.protobuf.Empty) {}
}

message CheckOwnershipRequest {
	string user_id = 1;
	string resource_type = 2;
	string resource_id = 3;
}

message CheckOwnershipResponse {
	bool is_owner = 1;
}

message RegisterOwnershipRequest {
	string resource_type = 1;
	string resource_id = 2;
	string owner_id = 3;
}

message RemoveOwnershipRequest {
	string resource_type = 1;
	string resource_id = 2;
}
