export enum Permission {
	EXAM_WRITE = 'exam:write',
	EXAM_REVIEW = 'exam:review',
	EXAM_APPROVE = 'exam:approve',
	USER_LOCK = 'user:lock',
	USER_BAN = 'user:ban',
	USER_UNLOCK = 'user:unlock',
	COURSE_ENROLL = 'course:enroll',
	COURSE_MANAGE = 'course:manage',
	BOOKING_CREATE = 'booking:create',
	BOOKING_MANAGE_SLOTS = 'booking:manage-slots',
	BOOKING_VIEW_ALL = 'booking:view-all',
	CONNECTION_REQUEST = 'connection:request',
	CONNECTION_VIEW_CHILD = 'connection:view-child',
	PAYMENT_READ = 'payment:read',
	PAYMENT_MANAGE = 'payment:manage',
	AI_PRACTICE_ACCESS = 'ai-practice:access',
	STUDENT_VIDEO_VIEW = 'student-video:view',
	STUDENT_VIDEO_MANAGE = 'student-video:manage',
	TEACHER_FEEDBACK_CREATE = 'teacher-feedback:create',
	TEACHER_FEEDBACK_VIEW = 'teacher-feedback:view',
	NOTIFICATION_SEND = 'notification:send',
	CHAT_ACCESS = 'chat:access',
	PROGRAM_MANAGE = 'program:manage',
	WEEKLY_FOCUS_MANAGE = 'weekly-focus:manage',
}
